//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.02.17 at 09:37:16 PM BRST 
//

package emulationstation;

import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * Generated from commadn xjc -d . gameList.xsd
 * 
 * <p>
 * Java class for anonymous complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="game" maxOccurs="unbounded">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="path" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="name" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="image" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="rating" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
 *                   &lt;element name="releasedate" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
 *                   &lt;element name="developer" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
 *                   &lt;element name="publisher" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
 *                   &lt;element name="genre" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
 *                   &lt;element name="players" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = { "games" })
@XmlRootElement(name = "gameList")
public class GameList {

	@XmlElement(name = "game", required = true)
	protected List<GameListGame> games = new ArrayList<GameListGame>();

	/**
	 * Gets the value of the game property.
	 * 
	 * <p>
	 * This accessor method returns a reference to the live list, not a snapshot. Therefore any modification you make to the returned list will be present inside the JAXB object. This is why there is not a <CODE>set</CODE> method for the game property.
	 * 
	 * <p>
	 * For example, to add a new item, do as follows:
	 * 
	 * <pre>
	 * getGame().add(newItem);
	 * </pre>
	 * 
	 * 
	 * <p>
	 * Objects of the following type(s) are allowed in the list {@link GameList.Game }
	 * 
	 * 
	 */
	public List<GameListGame> getGames() {
		if (games == null) {
			games = new ArrayList<GameListGame>();
		}
		return this.games;
	}

	public GameListGame findGameByPath(String name) {
		for (GameListGame game : games) {
			String esname = game.getPath().replace("./", "");
			esname = esname.substring(0, esname.lastIndexOf("."));
			if (esname.equals(name)) {
				return game;
			}
		}
		return null;
	}

	public void addGame(GameListGame game) {
		this.games.add(game);
	}

}
